# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

default-members = ["web-api"]
members = [
    "domain",
    "application",
    "infrastructure",
    "web-api"
]